name: CI

on:
  - 'pull_request'

permissions: {}

jobs:
  lint:
    runs-on: 'ubuntu-slim'
    permissions:
      contents: 'read'
    timeout-minutes: 5
    steps:
      - uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # v6
        with:
          persist-credentials: false
      - uses: 'cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15' # v31
      - run: |
          nix develop --command make lint
